current_env_name: '16_16'
tensorboard_comment: 'microrts_16_16_seed_10_loss_0'
seed: 0 # random seed
max_version: 10000
gae_lambda: 0.95 
gamma: 0.99 # discount factor
clip_coef: 0.2 # policy gradient loss clip 
max_clip_coef: 4 # ratio upper bound 
ent_coef: 0.01 # weight of entropy 
vf_coef: 1 # weight of value loss
learning_rate: 2.5e-4 # learning rate 
ratio_coef: 0.5 # weight of ratio 
grad_norm: 0.5 # max gradient normal of value 
mini_batch_size: 128 # minibatch size, which should divisible by an epdsode length 
gae_length: 256 # the length of generalized advantage estimator for calculating  
pg_loss_type: 0 # policy gradient type: 0 is discrete, 1 is continues, 2 is mixed and 3 is mixed policy gradient loss
enable_clip_max: True # whether clip value loss 
enable_ratio_decay: False # whether to decay ratio  
enable_entropy_decay: False # whether to decay entropy coefficient 
enable_lr_decay: False # whether to decay learning rate 
enable_grad_norm: False # whether to clip gradient norm 
enable_adv_norm: True # whether to normalize advantage function 
enable_mini_batch: False # whether to use mini batch 
num_envs: 64 # the number of environments 
use_gpu: True # whether to use GPU to training